### ISSUE TITLE
Update to latest match version of GOV.UK Design System

### ISSUE THREAD

**Issue by frankieroberto** [govuk-vue/govuk-vue#11]
Hi @matteason - are you planning to update this to match the latest version of the GOV.UK Design System?

Recent updates have been:

* change to the crown in the header
* change to the Tag component
* new Task list component
* new Exit this page component

Thanks! (I ask because we have this project listed on [x-govuk.github.io](https://x-govuk.github.io).)

**Comment by matteason** [comment]
Hi @frankieroberto  - yes, I'm planning to upgrade to v5 of the design system in the next couple of weeks

**Comment by frankieroberto** [comment]
> Hi @frankieroberto - yes, I'm planning to upgrade to v5 of the design system in the next couple of weeks

Amazing! Nice work.

Do you know of many live services using this library? Might be great to get them involved in testing the upgrade.

**Comment by matteason** [comment]
GOV.UK Vue has been updated to GOV.UK Frontend v5.6.0
